sudo: required
services:
  - docker

before_install:
  - docker build -t kevinlien/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kevinlien/react-test npm test -- --coverage

after_success:
  - docker build -t kevinlien/multi-client ./client
  - docker build -t kevinlien/multi-nginx ./nginx
  - docker build -t kevinlien/multi-server ./server
  - docker build -t kevinlien/multi-worker ./worker

  # Log into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push kevinlien/multi-client
  - docker push kevinlien/multi-nginx
  - docker push kevinlien/multi-server
  - docker push kevinlien/multi-worker